# Generated by Django 4.2.4 on 2023-08-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pst',
            new_name='Post',
        ),
    ]
